[project]
name = "pdf-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pypdf2>=3.0.1",
    "reportlab>=5.0.1",
    "streamlit>=1.63.0",
]

[project.scripts]
pdf-manager = "pdf_manager:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
